version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: ws
    versions:
    - 7.4.4
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: mime-types
    versions:
    - 2.1.29
